[universe]
raw = """
NASDAQ:GOOGL,
NASDAQ:AMZN,
NASDAQ:AMGN,
NASDAQ:AAPL,
NASDAQ:AMAT,
NASDAQ:ASML,
NASDAQ:BIIB,
NASDAQ:AVGO,
NASDAQ:CSCO,
NASDAQ:CSX,
NASDAQ:GILD,
NASDAQ:INTC,
NASDAQ:ISRG
NASDAQ:META,
NASDAQ:MU,
NASDAQ:MSFT,
NASDAQ:NDAQ,
NASDAQ:NVDA,
NASDAQ:PLTR,
NASDAQ:PEP,
NASDAQ:QCOM,
NASDAQ:ADP,
NASDAQ:PYPL,
NASDAQ:TXN,
NASDAQ:AMD,
NASDAQ:ADBE,
NASDAQ:MDLZ,
NASDAQ:CHTR,
NASDAQ:SBUX,
NASDAQ:CMCSA,
NASDAQ:BIDU,
NYSE:FI,
NASDAQ:COST,
NASDAQ:TMUS,
NASDAQ:NFLX,
"""
